Championships/Models/Tournament.cs
using Foolproof;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Championships.Models
{
    public class Tournament
    {

        public Tournament()
        {
            this.RegisteredUsers = new List<User>();
        }

        [Key]
        [Required]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        //[GreaterThan("Date", ErrorMessage = "Date of tournament must be greater than end of application deadline")]
        public DateTime Date { get; set; }

        [Required]
        [Display(Name = "Max amount of participants")]
        [Range(0, 10000)]
        public int MaxAmountOfUsers { get; set; }

        [Required]
        public string Discipline { get; set; }

        public string Organizer { get; set; }

        public string Sponsors { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name="End of application deadline")]
        public DateTime DateToRegister { get; set; }

        [Display(Name="Registered participants")]
        public virtual List<User> RegisteredUsers { get; set; }

    }
}

Championships/Controllers/TournamentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Championships.Models;
using MvcPaging;

namespace Championships.Controllers
{
    public class TournamentsController : Controller
    {
        private DashboardDbContext db = new DashboardDbContext();

        private int PageSize = 10;
        // GET: Tournaments
        public ActionResult Index(string searchText, int page = 0, string registered = "false")
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var tournaments = db.Tournaments.ToList();

            if (registered.Equals("true"))
            {
                string userMail = Session["UserMail"].ToString();

                var loggedUser = db.Users.Where(registeredUser => registeredUser.Mail.Equals(userMail)).FirstOrDefault();

                tournaments = tournaments.Where(tournament => tournament.RegisteredUsers.Contains(loggedUser)).ToList();
            }
            if (!String.IsNullOrEmpty(searchText))
            {
                tournaments = tournaments.Where(item => item.Name.Contains(searchText)).ToList();
            }

            var count = tournaments.Count();

            var data = tournaments.OrderBy(o => o.Name).Skip(page * PageSize).Take(PageSize).ToList();

            this.ViewBag.MaxPage = (count / PageSize) - (count % PageSize == 0 ? 1 : 0);

            this.ViewBag.Page = page;

            return this.View(data);
        }

        // GET: Tournaments/Details/5
        public ActionResult Details(string id)
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            string userMail = Session["UserMail"].ToString();
            var loggedUser = db.Users.Where(registeredUser => registeredUser.Mail.Equals(userMail)).FirstOrDefault();

            var model = new Tuple<Tournament, User>(
                tournament,
                loggedUser);

            return View(model);
        }

        public ActionResult TakePart(string id)
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Id = id;

            string userMail = Session["UserMail"].ToString();
            var loggedUser = db.Users.Where(registeredUser => registeredUser.Mail.Equals(userMail)).FirstOrDefault();

            Tournament tournament = db.Tournaments.Find(id);


            tournament.RegisteredUsers.Add(loggedUser);

            db.Tournaments.Attach(tournament);
            //db.Entry(tournament).State = EntityState.Modified;
            db.SaveChanges();
            //loggedUser.registeredTournaments.Add(tournament);

            //db.Users.Attach(loggedUser);
            //db.SaveChanges();
            //db.Entry(loggedUser).State = EntityState.Modified;
            //db.SaveChanges();

            return View();
        }

        // GET: Tournaments/Create
        public ActionResult Create()
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        // POST: Tournaments/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Date,MaxAmountOfUsers, Discipline, Sponsors, DateToRegister")] Tournament tournament)
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                if (db.Tournaments.Any(registeredTournament=> registeredTournament.Name == tournament.Name))
                {
                    Response.Write("<script>alert('Tournament with this name already exists');</script>");
                    return View();
                }

                tournament.Organizer = Session["UserMail"].ToString();

                db.Tournaments.Add(tournament);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tournament);
        }

        // GET: Tournaments/Edit/5
        public ActionResult Edit(string id)
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            return View(tournament);
        }

        // POST: Tournaments/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Name,Date,MaxAmountOfUsers, Discipline, Sponsors, DateToRegister")] Tournament tournament)
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                db.Entry(tournament).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tournament);
        }

        // GET: Tournaments/Delete/5
        public ActionResult Delete(string id)
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            return View(tournament);
        }

        // POST: Tournaments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Tournament tournament = db.Tournaments.Find(id);
            db.Tournaments.Remove(tournament);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Login/Create
        public ActionResult RegisterUserOnTournament()
        {
            if (@Session["UserMail"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Championships/Views/Tournaments/Create.cshtml
@model Championships.Models.Tournament

@{
    ViewBag.Title = "Create";
}

<h2>Create Tournament</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateToRegister, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateToRegister, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.DateToRegister, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaxAmountOfUsers, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxAmountOfUsers, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxAmountOfUsers, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Discipline, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Discipline, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Discipline, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sponsors, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sponsors, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sponsors, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Championships/Views/Tournaments/Delete.cshtml
@model Championships.Models.Tournament

@{
    ViewBag.Title = "Delete";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>
<div>
    <h4>Delete Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxAmountOfUsers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxAmountOfUsers)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Championships/Views/Tournaments/Details.cshtml
@using Championships.Models;
@model Tuple<Tournament, User>

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Item1.Name)</h2>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Item1.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.DateToRegister)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.DateToRegister)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.MaxAmountOfUsers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.MaxAmountOfUsers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.Discipline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Discipline)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.Organizer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Organizer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.Sponsors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.Sponsors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item1.RegisteredUsers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.RegisteredUsers.Count)
        </dd>

    </dl>
</div>
<p>

    @if (@Session["UserMail"].Equals("Guest"))
    {
        <p>You are just a guest, do you think you can participate in this?!</p>
    } else
    if (Model.Item2.registeredTournaments.Contains(Model.Item1))
    {
        <p>You are already registered in this tournament!</p>
    } else
    if (Model.Item2.Mail.Equals(Model.Item1.Organizer))
    {
        <p>You are organizer of this tournament</p>
    } else
    if (Model.Item1.RegisteredUsers.Count >= Model.Item1.MaxAmountOfUsers)
    {
        <p>There is no more space for another participant</p>
    } else
    if (Model.Item1.DateToRegister < DateTime.Now)
    {
        <p>Application time is over</p>

        <table class="table">
            <tr>
                <td>@Html.DisplayNameFor(model => model.Item2.Mail)</td>
            </tr>
            @foreach (var user in Model.Item1.RegisteredUsers)
            {
                <tr>
                    @Html.DisplayFor(modelItem => user.Mail)
                </tr>
            }
        </table>
    }
    else
    {
        @Html.ActionLink("Take part in this tournament!", "TakePart", "Tournaments", new { id = Model.Item1.Name }, new { @class = "btn btn-primary btn-lg" })
    }

    <br />
    @Html.ActionLink("Back to List", "Index")
    <br />

    @if (Model.Item1.Organizer != null && Model.Item1.Organizer.Equals(Session["UserMail"]))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Item1.Name })
    }


</p>

Championships/Views/Tournaments/Edit.cshtml
@model Championships.Models.Tournament

@{
    ViewBag.Title = "Edit";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Edit</h4>
    <hr />
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateToRegister, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateToRegister, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.DateToRegister, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaxAmountOfUsers, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxAmountOfUsers, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxAmountOfUsers, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Discipline, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Discipline, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Discipline, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sponsors, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sponsors, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sponsors, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Championships/Views/Tournaments/Index.cshtml
@model IEnumerable<Championships.Models.Tournament>

@{
    ViewBag.Title = "Tournaments";
}

<h2>All tournaments</h2>

@if (!Session["UserMail"].Equals("Guest"))
{
    <p>
        @Html.ActionLink("Create new Tournament", "Create")
    </p>
}

@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchText")
    </p>

    <p>
        @Html.RadioButton("registered", "true")<span>Show only tournaments where you are taking part</span><br />
        @Html.RadioButton("registered", "false")<span>Show all tournaments</span><br />
    </p>
    <input type="submit" value="Search" />
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxAmountOfUsers)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxAmountOfUsers)
            </td>
            @if (!@Session["UserMail"].Equals("Guest"))
            {
                <td>
                    @if (item.Organizer != null && item.Organizer.Equals(Session["UserMail"]))
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.Name }, new { @style = "float: left left-margin: 10px" })
                        @Html.ActionLink("Edit", "Edit", new { id = item.Name }, new { @style = "float: left left-margin: 10px" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Name }, new { @style = "float: left left-margin: 10px" })
                    }
                    else
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.Name }, new { @style = "float: left left-margin: 10px" })
                    }
                </td>
            }
            else
            {
                <td>
                    @Html.ActionLink("Sign in", "Login", "Login")
                </td>
            }
        </tr>
    }

    @if (ViewBag.Page > 0)
    {
        <a href="@Url.Action("Index", new { page = ViewBag.Page - 1 })"
           class="btn btn-default">
            &laquo; Prev
        </a>
    }
    @if (ViewBag.Page < ViewBag.MaxPage)
    {
        <a href="@Url.Action("Index", new { page = ViewBag.Page + 1 })"
           class="btn btn-default">
            Next &raquo;
        </a>
    }
    <caption>Page : @ViewBag.Page</caption>

</table>

Championships/Views/Tournaments/TakePart.cshtml
@model Championships.Models.User
@{
    ViewBag.Title = ViewBag.Id;
}

<h2>Tournament - @ViewBag.Id</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <h4>You have been succesfully registered on this tournament</h4>
}

<div>
    @Html.ActionLink("Back to list", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}